### ISSUE TITLE
ValueError: Failed to parse dbt manifest.json

### ISSUE THREAD

**Issue by jdavid459** [lightdash/dbt2looker#37]
Hey! 
I'm trying to run this package and hitting errors right after installation.  I pip installed dbt2looker, ran the following in the root of my dbt project.

```
dbt docs generate
dbt2looker
```

This gives me the following error:

> Traceback (most recent call last):
>   File "/Users/josh/.pyenv/versions/3.10.0/bin/dbt2looker", line 8, in <module>
>     sys.exit(run())
>   File "/Users/josh/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt2looker/cli.py", line 108, in run
>     raw_manifest = get_manifest(prefix=args.target_dir)
>   File "/Users/josh/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt2looker/cli.py", line 33, in get_manifest
>     parser.validate_manifest(raw_manifest)
>   File "/Users/josh/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt2looker/parser.py", line 20, in validate_manifest
>     raise ValueError("Failed to parse dbt manifest.json")
> ValueError: Failed to parse dbt manifest.json

This is preceded by a whole mess of error messages like such:

> 21:01:05 ERROR    Error in manifest at nodes.model.jaffle_shop.stg_customers.created_at: 1639274126.771925 is not of type 'integer'
> 21:01:05 ERROR    Error in manifest at nodes.model.jaffle_shop.stg_customers.resource_type: 'model' is not one of ['analysis']
> 21:01:05 ERROR    Error in manifest at nodes.model.jaffle_shop.stg_customers.created_at: 1639274126.771925 is not of type 'integer'
> 21:01:05 ERROR    Error in manifest at nodes.model.jaffle_shop.stg_customers.resource_type: 'model' is not one of ['test']

Any idea what might be going wrong here?  Happy to provide more detail.  Thank you!

**Comment by catherine-tanuwidjaja** [comment]
Hi, I am experiencing the same error as well.

**Comment by owlas** [comment]
Hey both @catherine-tanuwidjaja @jdavid459 apologies for this, I believe it's related to #41 - do you know which version of dbt you're running currently

**Comment by catherine-tanuwidjaja** [comment]
Hi @owlas , yes that looks right, I was using 1.0.

**Comment by owlas** [comment]
Thanks @catherine-tanuwidjaja - sorry for being so late for the dbt 1.0.0 release! Changes coming shortly!

**Comment by kning** [comment]
this fixed? I'm still getting the same error for dbt-snowflake v1.1.0

**Comment by owlas** [comment]
Hey @kning what version of dbt2looker are you using?
