### ISSUE TITLE
Support Bigquery BIGNUMERIC datatype

### ISSUE THREAD

**Issue by IL-Jerry** [lightdash/dbt2looker#39]
Previously, dbt2looker would not create dimension for field with data type BIGNUMERIC since Looker didn't support converting BIGNUMERIC. So when we ran `dbt2looker` in CLI there is a warning `WARNING Column type BIGNUMERIC not supported for conversion from bigquery to looker. No dimension will be created.`
However, as of November 2021, Looker has officially supported BigQuery BIGNUMBERIC ([link](https://docs.looker.com/relnotes/v21-changelog)). Please help to add this.
Thank you,

**Comment by owlas** [comment]
Hey @IL-Jerry - no problem, I can add this to the next release - expected this weekend

**Comment by IL-Jerry** [comment]
Thank you 😄
