### ISSUE TITLE
DBT version 1.0

### ISSUE THREAD

**Issue by AndreasTA-AW** [lightdash/dbt2looker#41]
Hi,

Is this library supporting DBT version 1.0 and forward? I can't get it to run at all.
There's a lot of errors when checking the schema of the manifest.json file.

/ Andrea

**Comment by owlas** [comment]
Hey @AndreasTA-AW - absolutely! I'll make an update this weekend to fix this

**Comment by joshuaballance** [comment]
Any update on this? I just stumbled upon this library and am also having issues using it with v1.0 or DBT. Thanks!

**Comment by ludogayet** [comment]
Same for me
